# Generated by Django 6.0.2 on 2026-03-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_category_options_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='moodle_course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
