# Generated by Django 6.0.2 on 2026-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_course_moodle_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='moodle_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
