# Generated by Django 6.0.2 on 2026-03-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_category_name_alter_course_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_mp4', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_mpd', models.FileField(blank=True, null=True, upload_to='dash/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='teacher.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
