# Generated by Django 6.0.2 on 2026-03-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_module'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'order')},
        ),
    ]
