# Generated by Django 6.0.2 on 2026-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_section_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='quiz_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='quiz_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='theory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(default='video', max_length=20),
        ),
    ]
