# Generated by Django 6.0.2 on 2026-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_module_quiz_answer_module_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='module',
            name='moodle_cmid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='moodle_module_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='mpd_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='moodle_section_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='quiz_options',
            field=models.TextField(blank=True, help_text='Store options as plain text or JSON string.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('theory', 'Theory'), ('quiz', 'Quiz')], default='video', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('section', 'order')},
        ),
    ]
