# Generated by Django 6.0.2 on 2026-03-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_category_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='section',
            name='moodle_section_number',
        ),
        migrations.AlterField(
            model_name='module',
            name='quiz_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(default='video', max_length=20),
        ),
        migrations.RemoveField(
            model_name='module',
            name='moodle_cmid',
        ),
        migrations.RemoveField(
            model_name='module',
            name='moodle_module_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='mpd_path',
        ),
        migrations.RemoveField(
            model_name='module',
            name='storage_path',
        ),
    ]
