# Generated by Django 6.0.2 on 2026-03-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_category_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='moodle_section_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
