# Generated by Django 6.0.2 on 2026-03-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_section_moodle_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz_type',
            field=models.CharField(blank=True, choices=[('mcq', 'MCQ'), ('true_false', 'True / False')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='quiz_options',
            field=models.TextField(blank=True, help_text='For MCQ, store options separated by commas or new lines.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('theory', 'Theory'), ('quiz', 'Quiz')], default='video', max_length=20),
        ),
    ]
