# Generated by Django 6.0.2 on 2026-03-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_module_quiz_type_alter_module_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('theory', 'Theory'), ('quiz', 'Quiz'), ('material', 'Material')], default='video', max_length=20),
        ),
    ]
