# Generated by Django 6.0.2 on 2026-03-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_module_material_file_alter_module_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='quiz_answer',
        ),
        migrations.RemoveField(
            model_name='module',
            name='quiz_options',
        ),
        migrations.RemoveField(
            model_name='module',
            name='quiz_question',
        ),
        migrations.RemoveField(
            model_name='module',
            name='quiz_type',
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('quiz_type', models.CharField(choices=[('mcq', 'MCQ'), ('true_false', 'True / False')], max_length=20)),
                ('options', models.TextField(blank=True, help_text='For MCQ, store options line by line.', null=True)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher.module')),
            ],
        ),
    ]
