# Generated by Django 6.0.2 on 2026-03-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_remove_module_quiz_answer_remove_module_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='moodle_category_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='moodle_course_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='moodle_section_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
