# Generated by Django 6.0.2 on 2026-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_alter_category_moodle_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='moodle_cmid',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='moodle_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='moodle_module_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
