# Generated by Django 6.0.2 on 2026-04-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_module_moodle_cmid_module_moodle_instance_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='This certificate is proudly presented to', max_length=255)),
                ('organization_name', models.CharField(default='Cryptographic Adaptive LMS', max_length=255)),
                ('issuer_name', models.CharField(blank=True, default='Instructor', max_length=255)),
                ('signer_name', models.CharField(blank=True, default='Authorized Signature', max_length=255)),
                ('signer_role', models.CharField(blank=True, default='Instructor', max_length=255)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate/signatures/')),
                ('seal_image', models.ImageField(blank=True, null=True, upload_to='certificate/seals/')),
                ('verify_label', models.CharField(blank=True, default='Verify via LMS QR record', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Settings',
                'verbose_name_plural': 'Certificate Settings',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
