# Generated by Django 6.0.2 on 2026-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
