# Generated by Django 6.0.2 on 2026-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_host', models.CharField(default='http://127.0.0.1:8000', max_length=255)),
                ('token_expiry_seconds', models.PositiveIntegerField(default=300)),
                ('certificate_signer', models.CharField(default='Authorized Signature', max_length=255)),
                ('signer_role', models.CharField(default='Instructor', max_length=255)),
                ('verification_label', models.CharField(default='Verify via LMS QR record', max_length=255)),
                ('qr_verification_enabled', models.BooleanField(default=True)),
                ('secure_streaming_enabled', models.BooleanField(default=True)),
                ('watch_validation_percent', models.PositiveIntegerField(default=90)),
                ('quiz_completion_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
