# Generated by Django 6.0.2 on 2026-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='moodle_admin_id',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='moodle_base_url',
            field=models.CharField(default='http://127.0.0.1/moodle', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='moodle_student_role',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='moodle_teacher_role',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='moodle_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
