# Generated by Django 6.0.2 on 2026-04-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_options_and_more'),
        ('teacher', '0019_module_moodle_cmid_module_moodle_instance_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('heartbeat', 'Heartbeat'), ('seek', 'Seek'), ('ended', 'Ended')], default='heartbeat', max_length=20)),
                ('current_time', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_events', to='teacher.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoWatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.FloatField(default=0)),
                ('watched_seconds', models.FloatField(default=0)),
                ('watched_percent', models.FloatField(default=0)),
                ('last_position', models.FloatField(default=0)),
                ('max_position_reached', models.FloatField(default=0)),
                ('heartbeat_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_progress', to='teacher.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_heartbeat_at', '-started_at'],
                'unique_together': {('student', 'module')},
            },
        ),
    ]
