# Generated by Django 6.0.2 on 2026-04-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_videowatchevent_videowatchprogress'),
        ('teacher', '0019_module_moodle_cmid_module_moodle_instance_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabSwitchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switched_at', models.DateTimeField(auto_now_add=True)),
                ('current_time', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_switch_logs', to='teacher.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_switch_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-switched_at'],
            },
        ),
        migrations.CreateModel(
            name='WebcamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='webcam_snapshots/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_snapshots', to='teacher.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
