# Generated by Django 6.0.2 on 2026-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_tabswitchlog_webcamsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabswitchlog',
            name='current_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='tabswitchlog',
            name='previous_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='videowatchevent',
            name='current_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='videowatchevent',
            name='previous_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='webcamsnapshot',
            name='current_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='webcamsnapshot',
            name='previous_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
